"""Inicial

Revision ID: d8f9c2c7d6ee
Revises: 
Create Date: 2025-11-14 12:06:12.248849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f9c2c7d6ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('ID_Categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre_Categoria', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ID_Categoria'),
    sa.UniqueConstraint('Nombre_Categoria')
    )
    op.create_table('estado',
    sa.Column('ID_Estado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre_estado', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ID_Estado'),
    sa.UniqueConstraint('Nombre_estado')
    )
    op.create_table('facultad',
    sa.Column('ID_Facultad', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('ID_Facultad')
    )
    op.create_table('roles',
    sa.Column('ID_Roles', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre_Rol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ID_Roles'),
    sa.UniqueConstraint('Nombre_Rol')
    )
    op.create_table('sede',
    sa.Column('ID_Sede', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Ubicacion', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('ID_Sede')
    )
    op.create_table('usuario',
    sa.Column('ID_Usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ID_Usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('club',
    sa.Column('ID_Club', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(length=150), nullable=False),
    sa.Column('Descripcion', sa.Text(), nullable=True),
    sa.Column('Tipo', sa.String(length=100), nullable=True),
    sa.Column('Duracion', sa.String(length=50), nullable=True),
    sa.Column('ID_Sede', sa.Integer(), nullable=False),
    sa.Column('ID_Facultad', sa.Integer(), nullable=True),
    sa.Column('ID_Estado', sa.Integer(), nullable=False),
    sa.Column('ID_Usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Estado'], ['estado.ID_Estado'], ),
    sa.ForeignKeyConstraint(['ID_Facultad'], ['facultad.ID_Facultad'], ),
    sa.ForeignKeyConstraint(['ID_Sede'], ['sede.ID_Sede'], ),
    sa.ForeignKeyConstraint(['ID_Usuario'], ['usuario.ID_Usuario'], ),
    sa.PrimaryKeyConstraint('ID_Club')
    )
    op.create_table('persona',
    sa.Column('ID_Persona', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=False),
    sa.Column('Apellido', sa.String(length=100), nullable=False),
    sa.Column('Carrera', sa.String(length=150), nullable=True),
    sa.Column('Correo_institucional', sa.String(length=150), nullable=True),
    sa.Column('Cantidad', sa.Integer(), nullable=True),
    sa.Column('Edad', sa.Integer(), nullable=True),
    sa.Column('Cedula', sa.String(length=20), nullable=True),
    sa.Column('Telefono', sa.String(length=20), nullable=True),
    sa.Column('ID_Estado', sa.Integer(), nullable=False),
    sa.Column('ID_Usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Estado'], ['estado.ID_Estado'], ),
    sa.ForeignKeyConstraint(['ID_Usuario'], ['usuario.ID_Usuario'], ),
    sa.PrimaryKeyConstraint('ID_Persona'),
    sa.UniqueConstraint('Cedula'),
    sa.UniqueConstraint('Correo_institucional')
    )
    op.create_table('actividad',
    sa.Column('ID_Actividad', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(length=150), nullable=False),
    sa.Column('Descripcion', sa.Text(), nullable=True),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('Lugar', sa.String(length=200), nullable=True),
    sa.Column('ID_Club', sa.Integer(), nullable=False),
    sa.Column('ID_Estado', sa.Integer(), nullable=False),
    sa.Column('ID_Usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Club'], ['club.ID_Club'], ),
    sa.ForeignKeyConstraint(['ID_Estado'], ['estado.ID_Estado'], ),
    sa.ForeignKeyConstraint(['ID_Usuario'], ['usuario.ID_Usuario'], ),
    sa.PrimaryKeyConstraint('ID_Actividad')
    )
    op.create_table('inscripcion',
    sa.Column('ID_Inscripcion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_Persona', sa.Integer(), nullable=False),
    sa.Column('ID_Club', sa.Integer(), nullable=False),
    sa.Column('ID_Roles', sa.Integer(), nullable=False),
    sa.Column('Fecha_Ingreso', sa.DateTime(), nullable=True),
    sa.Column('ID_Estado', sa.Integer(), nullable=False),
    sa.Column('ID_Usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Club'], ['club.ID_Club'], ),
    sa.ForeignKeyConstraint(['ID_Estado'], ['estado.ID_Estado'], ),
    sa.ForeignKeyConstraint(['ID_Persona'], ['persona.ID_Persona'], ),
    sa.ForeignKeyConstraint(['ID_Roles'], ['roles.ID_Roles'], ),
    sa.ForeignKeyConstraint(['ID_Usuario'], ['usuario.ID_Usuario'], ),
    sa.PrimaryKeyConstraint('ID_Inscripcion'),
    sa.UniqueConstraint('ID_Persona', 'ID_Club', name='uq_persona_club')
    )
    op.create_table('actividades_realizadas',
    sa.Column('ID_Participacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_Estudiante', sa.Integer(), nullable=False),
    sa.Column('ID_Actividad', sa.Integer(), nullable=False),
    sa.Column('ID_Roles', sa.Integer(), nullable=False),
    sa.Column('ID_Estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Actividad'], ['actividad.ID_Actividad'], ),
    sa.ForeignKeyConstraint(['ID_Estado'], ['estado.ID_Estado'], ),
    sa.ForeignKeyConstraint(['ID_Estudiante'], ['persona.ID_Persona'], ),
    sa.ForeignKeyConstraint(['ID_Roles'], ['roles.ID_Roles'], ),
    sa.PrimaryKeyConstraint('ID_Participacion'),
    sa.UniqueConstraint('ID_Estudiante', 'ID_Actividad', name='uq_estudiante_actividad')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actividades_realizadas')
    op.drop_table('inscripcion')
    op.drop_table('actividad')
    op.drop_table('persona')
    op.drop_table('club')
    op.drop_table('usuario')
    op.drop_table('sede')
    op.drop_table('roles')
    op.drop_table('facultad')
    op.drop_table('estado')
    op.drop_table('categoria')
    # ### end Alembic commands ###
